'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AllergenEntity
    Public Property allID As Integer
    Public Property allBezeichnung As String

    Public Overridable Property tblKunden As ICollection(Of KundeEntity) = New HashSet(Of KundeEntity)
    Public Overridable Property tblKunden1 As ICollection(Of KundeEntity) = New HashSet(Of KundeEntity)
    Public Overridable Property tblKunden2 As ICollection(Of KundeEntity) = New HashSet(Of KundeEntity)
    Public Overridable Property tblKunden3 As ICollection(Of KundeEntity) = New HashSet(Of KundeEntity)
    Public Overridable Property tblKunden4 As ICollection(Of KundeEntity) = New HashSet(Of KundeEntity)

End Class
