'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AuftragEntity
    Public Property aufID As Integer
    Public Property aufkndKunde As Integer
    Public Property aufkreKreation As Integer
    Public Property aufautAutomat As Integer

    Public Overridable Property tblAutomaten As AutomatEntity
    Public Overridable Property tblKunden As KundeEntity
    Public Overridable Property tblKreationen As KreationEntity

End Class
