'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AutomatEntity
    Public Property autID As Integer
    Public Property autSeriennummer As String
    Public Property autSoftwareversion As Integer
    Public Property autStandort As String
    Public Property autZutatenVorraete As Integer

    Public Overridable Property tblAuftraege As ICollection(Of AuftragEntity) = New HashSet(Of AuftragEntity)
    Public Overridable Property tblZutatenVorraete As ZutatVorraeteEntity

End Class
