'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class CustomCoffeeDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CustomCoffeeDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property tblAllergene() As DbSet(Of AllergenEntity)
    Public Property tblAuftraege() As DbSet(Of AuftragEntity)
    Public Property tblAutomaten() As DbSet(Of AutomatEntity)
    Public Property tblKategorien() As DbSet(Of KategorieEntity)
    Public Property tblKreationen() As DbSet(Of KreationEntity)
    Public Property tblKunden() As DbSet(Of KundeEntity)
    Public Property tblZutaten() As DbSet(Of ZutatEntity)
    Public Property tblZutatenVorraete() As DbSet(Of ZutatVorraeteEntity)

End Class
