'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class KategorieEntity
    Public Property katID As Integer
    Public Property katBezeichnung As String

    Public Overridable Property tblZutaten As ICollection(Of ZutatEntity) = New HashSet(Of ZutatEntity)

End Class
