'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class KreationEntity
    Public Property kreID As Integer
    Public Property kreBezeichnung As String
    Public Property krePreis As Decimal
    Public Property kreLikeAnzahl As Nullable(Of Long)
    Public Property krezutBasis As Zutat
    Public Property krezutExtra1 As Zutat
    Public Property krezutExtra2 As Zutat
    Public Property krezutMilch As Zutat
    Public Property krezutTopping As Zutat

    Public Overridable Property tblAuftraege As ICollection(Of AuftragEntity) = New HashSet(Of AuftragEntity)
    Public Overridable Property tblZutaten As ZutatEntity
    Public Overridable Property tblZutaten1 As ZutatEntity
    Public Overridable Property tblZutaten2 As ZutatEntity
    Public Overridable Property tblZutaten3 As ZutatEntity
    Public Overridable Property tblZutaten4 As ZutatEntity

End Class
