'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class KundeEntity
    Public Property kndID As Integer
    Public Property kndBenutzername As String
    Public Property kndName As String
    Public Property kndVorname As String
    Public Property kndGebDatum As String
    Public Property kndallAllergen1 As Nullable(Of Integer)
    Public Property kndallAllergen2 As Nullable(Of Integer)
    Public Property kndallAllergen3 As Nullable(Of Integer)
    Public Property kndallAllergen4 As Nullable(Of Integer)
    Public Property kndallAllergen5 As Nullable(Of Integer)
    Public Property kndzutLieblingsmilch As Integer

    Public Overridable Property tblAllergene As AllergenEntity
    Public Overridable Property tblAllergene1 As AllergenEntity
    Public Overridable Property tblAllergene2 As AllergenEntity
    Public Overridable Property tblAllergene3 As AllergenEntity
    Public Overridable Property tblAllergene4 As AllergenEntity
    Public Overridable Property tblAuftraege As ICollection(Of AuftragEntity) = New HashSet(Of AuftragEntity)
    Public Overridable Property tblZutaten As ZutatEntity

End Class
