'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ZutatVorraeteEntity
    Public Property Id As Integer
    Public Property zutvorMenge As String

    Public Overridable Property tblAutomaten As ICollection(Of AutomatEntity) = New HashSet(Of AutomatEntity)

End Class
