'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace CustomCoffeeServiceReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Kunde", [Namespace]:="http://schemas.datacontract.org/2004/07/CustomCoffee"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Kunde
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Allergen1Field As CustomCoffeeServiceReference.Allergen
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Allergen2Field As CustomCoffeeServiceReference.Allergen
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Allergen3Field As CustomCoffeeServiceReference.Allergen
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Allergen4Field As CustomCoffeeServiceReference.Allergen
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Allergen5Field As CustomCoffeeServiceReference.Allergen
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AuftraegeField As System.Collections.Generic.List(Of CustomCoffeeServiceReference.Auftrag)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LieblingsmilchField As CustomCoffeeServiceReference.Zutat
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private datGebDatField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private strBenutzernameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private strNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private strVornameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Allergen1() As CustomCoffeeServiceReference.Allergen
            Get
                Return Me.Allergen1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Allergen1Field, value) <> true) Then
                    Me.Allergen1Field = value
                    Me.RaisePropertyChanged("Allergen1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Allergen2() As CustomCoffeeServiceReference.Allergen
            Get
                Return Me.Allergen2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Allergen2Field, value) <> true) Then
                    Me.Allergen2Field = value
                    Me.RaisePropertyChanged("Allergen2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Allergen3() As CustomCoffeeServiceReference.Allergen
            Get
                Return Me.Allergen3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Allergen3Field, value) <> true) Then
                    Me.Allergen3Field = value
                    Me.RaisePropertyChanged("Allergen3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Allergen4() As CustomCoffeeServiceReference.Allergen
            Get
                Return Me.Allergen4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Allergen4Field, value) <> true) Then
                    Me.Allergen4Field = value
                    Me.RaisePropertyChanged("Allergen4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Allergen5() As CustomCoffeeServiceReference.Allergen
            Get
                Return Me.Allergen5Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Allergen5Field, value) <> true) Then
                    Me.Allergen5Field = value
                    Me.RaisePropertyChanged("Allergen5")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Auftraege() As System.Collections.Generic.List(Of CustomCoffeeServiceReference.Auftrag)
            Get
                Return Me.AuftraegeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AuftraegeField, value) <> true) Then
                    Me.AuftraegeField = value
                    Me.RaisePropertyChanged("Auftraege")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Lieblingsmilch() As CustomCoffeeServiceReference.Zutat
            Get
                Return Me.LieblingsmilchField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LieblingsmilchField, value) <> true) Then
                    Me.LieblingsmilchField = value
                    Me.RaisePropertyChanged("Lieblingsmilch")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property datGebDat() As Date
            Get
                Return Me.datGebDatField
            End Get
            Set
                If (Me.datGebDatField.Equals(value) <> true) Then
                    Me.datGebDatField = value
                    Me.RaisePropertyChanged("datGebDat")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property strBenutzername() As String
            Get
                Return Me.strBenutzernameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.strBenutzernameField, value) <> true) Then
                    Me.strBenutzernameField = value
                    Me.RaisePropertyChanged("strBenutzername")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property strName() As String
            Get
                Return Me.strNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.strNameField, value) <> true) Then
                    Me.strNameField = value
                    Me.RaisePropertyChanged("strName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property strVorname() As String
            Get
                Return Me.strVornameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.strVornameField, value) <> true) Then
                    Me.strVornameField = value
                    Me.RaisePropertyChanged("strVorname")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Allergen", [Namespace]:="http://schemas.datacontract.org/2004/07/CustomCoffee"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Allergen
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private intIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private strBezeichnungField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property intID() As Integer
            Get
                Return Me.intIDField
            End Get
            Set
                If (Me.intIDField.Equals(value) <> true) Then
                    Me.intIDField = value
                    Me.RaisePropertyChanged("intID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property strBezeichnung() As String
            Get
                Return Me.strBezeichnungField
            End Get
            Set
                If (Object.ReferenceEquals(Me.strBezeichnungField, value) <> true) Then
                    Me.strBezeichnungField = value
                    Me.RaisePropertyChanged("strBezeichnung")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Zutat", [Namespace]:="http://schemas.datacontract.org/2004/07/CustomCoffee"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Zutat
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BezeichnungField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KategorieField As CustomCoffeeServiceReference.Kategorie
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Bezeichnung() As String
            Get
                Return Me.BezeichnungField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BezeichnungField, value) <> true) Then
                    Me.BezeichnungField = value
                    Me.RaisePropertyChanged("Bezeichnung")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As Integer
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Kategorie() As CustomCoffeeServiceReference.Kategorie
            Get
                Return Me.KategorieField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KategorieField, value) <> true) Then
                    Me.KategorieField = value
                    Me.RaisePropertyChanged("Kategorie")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Auftrag", [Namespace]:="http://schemas.datacontract.org/2004/07/CustomCoffee"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Auftrag
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AutomatField As CustomCoffeeServiceReference.Automat
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KreationField As CustomCoffeeServiceReference.Kreation
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KundeField As CustomCoffeeServiceReference.Kunde
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Automat() As CustomCoffeeServiceReference.Automat
            Get
                Return Me.AutomatField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AutomatField, value) <> true) Then
                    Me.AutomatField = value
                    Me.RaisePropertyChanged("Automat")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As Integer
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Kreation() As CustomCoffeeServiceReference.Kreation
            Get
                Return Me.KreationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KreationField, value) <> true) Then
                    Me.KreationField = value
                    Me.RaisePropertyChanged("Kreation")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Kunde() As CustomCoffeeServiceReference.Kunde
            Get
                Return Me.KundeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KundeField, value) <> true) Then
                    Me.KundeField = value
                    Me.RaisePropertyChanged("Kunde")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Automat", [Namespace]:="http://schemas.datacontract.org/2004/07/CustomCoffee"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Automat
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SeriennummerField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SoftwareversionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StandortField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ZutatenVorraeteField As System.Collections.Generic.List(Of CustomCoffeeServiceReference.ZutatenVorrat)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As Integer
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Seriennummer() As String
            Get
                Return Me.SeriennummerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SeriennummerField, value) <> true) Then
                    Me.SeriennummerField = value
                    Me.RaisePropertyChanged("Seriennummer")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Softwareversion() As String
            Get
                Return Me.SoftwareversionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SoftwareversionField, value) <> true) Then
                    Me.SoftwareversionField = value
                    Me.RaisePropertyChanged("Softwareversion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Standort() As String
            Get
                Return Me.StandortField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StandortField, value) <> true) Then
                    Me.StandortField = value
                    Me.RaisePropertyChanged("Standort")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ZutatenVorraete() As System.Collections.Generic.List(Of CustomCoffeeServiceReference.ZutatenVorrat)
            Get
                Return Me.ZutatenVorraeteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ZutatenVorraeteField, value) <> true) Then
                    Me.ZutatenVorraeteField = value
                    Me.RaisePropertyChanged("ZutatenVorraete")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Kreation", [Namespace]:="http://schemas.datacontract.org/2004/07/CustomCoffee"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Kreation
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BasisField As CustomCoffeeServiceReference.Zutat
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BezeichnungField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Extra1Field As CustomCoffeeServiceReference.Zutat
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Extra2Field As CustomCoffeeServiceReference.Zutat
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KundeField As CustomCoffeeServiceReference.Kunde
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LikeAnzahlField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MilchField As CustomCoffeeServiceReference.Zutat
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PreisField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ToppingField As CustomCoffeeServiceReference.Zutat
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Basis() As CustomCoffeeServiceReference.Zutat
            Get
                Return Me.BasisField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BasisField, value) <> true) Then
                    Me.BasisField = value
                    Me.RaisePropertyChanged("Basis")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Bezeichnung() As String
            Get
                Return Me.BezeichnungField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BezeichnungField, value) <> true) Then
                    Me.BezeichnungField = value
                    Me.RaisePropertyChanged("Bezeichnung")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Extra1() As CustomCoffeeServiceReference.Zutat
            Get
                Return Me.Extra1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Extra1Field, value) <> true) Then
                    Me.Extra1Field = value
                    Me.RaisePropertyChanged("Extra1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Extra2() As CustomCoffeeServiceReference.Zutat
            Get
                Return Me.Extra2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Extra2Field, value) <> true) Then
                    Me.Extra2Field = value
                    Me.RaisePropertyChanged("Extra2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As Integer
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Kunde() As CustomCoffeeServiceReference.Kunde
            Get
                Return Me.KundeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KundeField, value) <> true) Then
                    Me.KundeField = value
                    Me.RaisePropertyChanged("Kunde")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LikeAnzahl() As Integer
            Get
                Return Me.LikeAnzahlField
            End Get
            Set
                If (Me.LikeAnzahlField.Equals(value) <> true) Then
                    Me.LikeAnzahlField = value
                    Me.RaisePropertyChanged("LikeAnzahl")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Milch() As CustomCoffeeServiceReference.Zutat
            Get
                Return Me.MilchField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MilchField, value) <> true) Then
                    Me.MilchField = value
                    Me.RaisePropertyChanged("Milch")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Preis() As Double
            Get
                Return Me.PreisField
            End Get
            Set
                If (Me.PreisField.Equals(value) <> true) Then
                    Me.PreisField = value
                    Me.RaisePropertyChanged("Preis")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Topping() As CustomCoffeeServiceReference.Zutat
            Get
                Return Me.ToppingField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ToppingField, value) <> true) Then
                    Me.ToppingField = value
                    Me.RaisePropertyChanged("Topping")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ZutatenVorrat", [Namespace]:="http://schemas.datacontract.org/2004/07/CustomCoffee"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ZutatenVorrat
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MengeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ZutatField As CustomCoffeeServiceReference.Zutat
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Menge() As Integer
            Get
                Return Me.MengeField
            End Get
            Set
                If (Me.MengeField.Equals(value) <> true) Then
                    Me.MengeField = value
                    Me.RaisePropertyChanged("Menge")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Zutat() As CustomCoffeeServiceReference.Zutat
            Get
                Return Me.ZutatField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ZutatField, value) <> true) Then
                    Me.ZutatField = value
                    Me.RaisePropertyChanged("Zutat")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Kategorie", [Namespace]:="http://schemas.datacontract.org/2004/07/CustomCoffee"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Kategorie
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BasisField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Extra1Field As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Extra2Field As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MilchField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TopppingField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Basis() As Integer
            Get
                Return Me.BasisField
            End Get
            Set
                If (Me.BasisField.Equals(value) <> true) Then
                    Me.BasisField = value
                    Me.RaisePropertyChanged("Basis")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Extra1() As Integer
            Get
                Return Me.Extra1Field
            End Get
            Set
                If (Me.Extra1Field.Equals(value) <> true) Then
                    Me.Extra1Field = value
                    Me.RaisePropertyChanged("Extra1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Extra2() As Integer
            Get
                Return Me.Extra2Field
            End Get
            Set
                If (Me.Extra2Field.Equals(value) <> true) Then
                    Me.Extra2Field = value
                    Me.RaisePropertyChanged("Extra2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As Integer
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Milch() As Integer
            Get
                Return Me.MilchField
            End Get
            Set
                If (Me.MilchField.Equals(value) <> true) Then
                    Me.MilchField = value
                    Me.RaisePropertyChanged("Milch")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Toppping() As Integer
            Get
                Return Me.TopppingField
            End Get
            Set
                If (Me.TopppingField.Equals(value) <> true) Then
                    Me.TopppingField = value
                    Me.RaisePropertyChanged("Toppping")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="CustomCoffeeServiceReference.ICustomCoffeeService")>  _
    Public Interface ICustomCoffeeService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICustomCoffeeService/GibKunde", ReplyAction:="http://tempuri.org/ICustomCoffeeService/GibKundeResponse")>  _
        Function GibKunde(ByVal pstrBenutzername As CustomCoffeeServiceReference.Kunde) As System.Collections.Generic.List(Of CustomCoffeeServiceReference.Kunde)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICustomCoffeeService/GibKunde", ReplyAction:="http://tempuri.org/ICustomCoffeeService/GibKundeResponse")>  _
        Function GibKundeAsync(ByVal pstrBenutzername As CustomCoffeeServiceReference.Kunde) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of CustomCoffeeServiceReference.Kunde))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICustomCoffeeService/GibMeineKreationen", ReplyAction:="http://tempuri.org/ICustomCoffeeService/GibMeineKreationenResponse")>  _
        Function GibMeineKreationen() As System.Collections.Generic.List(Of CustomCoffeeServiceReference.Kreation)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICustomCoffeeService/GibMeineKreationen", ReplyAction:="http://tempuri.org/ICustomCoffeeService/GibMeineKreationenResponse")>  _
        Function GibMeineKreationenAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of CustomCoffeeServiceReference.Kreation))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICustomCoffeeService/GibKreation", ReplyAction:="http://tempuri.org/ICustomCoffeeService/GibKreationResponse")>  _
        Function GibKreation(ByVal pintID As Integer) As CustomCoffeeServiceReference.Kreation
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICustomCoffeeService/GibKreation", ReplyAction:="http://tempuri.org/ICustomCoffeeService/GibKreationResponse")>  _
        Function GibKreationAsync(ByVal pintID As Integer) As System.Threading.Tasks.Task(Of CustomCoffeeServiceReference.Kreation)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICustomCoffeeService/ErstelleNeueKreation", ReplyAction:="http://tempuri.org/ICustomCoffeeService/ErstelleNeueKreationResponse")>  _
        Function ErstelleNeueKreation(ByVal pintBasis As Integer, ByVal pintExtra1 As Integer, ByVal pintExtra2 As Integer, ByVal pintMilch As Integer, ByVal pintTopping As Integer) As CustomCoffeeServiceReference.Kreation
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICustomCoffeeService/ErstelleNeueKreation", ReplyAction:="http://tempuri.org/ICustomCoffeeService/ErstelleNeueKreationResponse")>  _
        Function ErstelleNeueKreationAsync(ByVal pintBasis As Integer, ByVal pintExtra1 As Integer, ByVal pintExtra2 As Integer, ByVal pintMilch As Integer, ByVal pintTopping As Integer) As System.Threading.Tasks.Task(Of CustomCoffeeServiceReference.Kreation)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICustomCoffeeService/ladeAlleZutaten", ReplyAction:="http://tempuri.org/ICustomCoffeeService/ladeAlleZutatenResponse")>  _
        Function ladeAlleZutaten() As System.Collections.Generic.List(Of CustomCoffeeServiceReference.Zutat)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICustomCoffeeService/ladeAlleZutaten", ReplyAction:="http://tempuri.org/ICustomCoffeeService/ladeAlleZutatenResponse")>  _
        Function ladeAlleZutatenAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of CustomCoffeeServiceReference.Zutat))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICustomCoffeeService/BerechneEntfernung", ReplyAction:="http://tempuri.org/ICustomCoffeeService/BerechneEntfernungResponse")>  _
        Function BerechneEntfernung() As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICustomCoffeeService/BerechneEntfernung", ReplyAction:="http://tempuri.org/ICustomCoffeeService/BerechneEntfernungResponse")>  _
        Function BerechneEntfernungAsync() As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICustomCoffeeService/BestelleKreation", ReplyAction:="http://tempuri.org/ICustomCoffeeService/BestelleKreationResponse")>  _
        Function BestelleKreation(ByVal pKreation As CustomCoffeeServiceReference.Kreation) As CustomCoffeeServiceReference.Auftrag
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICustomCoffeeService/BestelleKreation", ReplyAction:="http://tempuri.org/ICustomCoffeeService/BestelleKreationResponse")>  _
        Function BestelleKreationAsync(ByVal pKreation As CustomCoffeeServiceReference.Kreation) As System.Threading.Tasks.Task(Of CustomCoffeeServiceReference.Auftrag)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ICustomCoffeeServiceChannel
        Inherits CustomCoffeeServiceReference.ICustomCoffeeService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CustomCoffeeServiceClient
        Inherits System.ServiceModel.ClientBase(Of CustomCoffeeServiceReference.ICustomCoffeeService)
        Implements CustomCoffeeServiceReference.ICustomCoffeeService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GibKunde(ByVal pstrBenutzername As CustomCoffeeServiceReference.Kunde) As System.Collections.Generic.List(Of CustomCoffeeServiceReference.Kunde) Implements CustomCoffeeServiceReference.ICustomCoffeeService.GibKunde
            Return MyBase.Channel.GibKunde(pstrBenutzername)
        End Function
        
        Public Function GibKundeAsync(ByVal pstrBenutzername As CustomCoffeeServiceReference.Kunde) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of CustomCoffeeServiceReference.Kunde)) Implements CustomCoffeeServiceReference.ICustomCoffeeService.GibKundeAsync
            Return MyBase.Channel.GibKundeAsync(pstrBenutzername)
        End Function
        
        Public Function GibMeineKreationen() As System.Collections.Generic.List(Of CustomCoffeeServiceReference.Kreation) Implements CustomCoffeeServiceReference.ICustomCoffeeService.GibMeineKreationen
            Return MyBase.Channel.GibMeineKreationen
        End Function
        
        Public Function GibMeineKreationenAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of CustomCoffeeServiceReference.Kreation)) Implements CustomCoffeeServiceReference.ICustomCoffeeService.GibMeineKreationenAsync
            Return MyBase.Channel.GibMeineKreationenAsync
        End Function
        
        Public Function GibKreation(ByVal pintID As Integer) As CustomCoffeeServiceReference.Kreation Implements CustomCoffeeServiceReference.ICustomCoffeeService.GibKreation
            Return MyBase.Channel.GibKreation(pintID)
        End Function
        
        Public Function GibKreationAsync(ByVal pintID As Integer) As System.Threading.Tasks.Task(Of CustomCoffeeServiceReference.Kreation) Implements CustomCoffeeServiceReference.ICustomCoffeeService.GibKreationAsync
            Return MyBase.Channel.GibKreationAsync(pintID)
        End Function
        
        Public Function ErstelleNeueKreation(ByVal pintBasis As Integer, ByVal pintExtra1 As Integer, ByVal pintExtra2 As Integer, ByVal pintMilch As Integer, ByVal pintTopping As Integer) As CustomCoffeeServiceReference.Kreation Implements CustomCoffeeServiceReference.ICustomCoffeeService.ErstelleNeueKreation
            Return MyBase.Channel.ErstelleNeueKreation(pintBasis, pintExtra1, pintExtra2, pintMilch, pintTopping)
        End Function
        
        Public Function ErstelleNeueKreationAsync(ByVal pintBasis As Integer, ByVal pintExtra1 As Integer, ByVal pintExtra2 As Integer, ByVal pintMilch As Integer, ByVal pintTopping As Integer) As System.Threading.Tasks.Task(Of CustomCoffeeServiceReference.Kreation) Implements CustomCoffeeServiceReference.ICustomCoffeeService.ErstelleNeueKreationAsync
            Return MyBase.Channel.ErstelleNeueKreationAsync(pintBasis, pintExtra1, pintExtra2, pintMilch, pintTopping)
        End Function
        
        Public Function ladeAlleZutaten() As System.Collections.Generic.List(Of CustomCoffeeServiceReference.Zutat) Implements CustomCoffeeServiceReference.ICustomCoffeeService.ladeAlleZutaten
            Return MyBase.Channel.ladeAlleZutaten
        End Function
        
        Public Function ladeAlleZutatenAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of CustomCoffeeServiceReference.Zutat)) Implements CustomCoffeeServiceReference.ICustomCoffeeService.ladeAlleZutatenAsync
            Return MyBase.Channel.ladeAlleZutatenAsync
        End Function
        
        Public Function BerechneEntfernung() As Integer Implements CustomCoffeeServiceReference.ICustomCoffeeService.BerechneEntfernung
            Return MyBase.Channel.BerechneEntfernung
        End Function
        
        Public Function BerechneEntfernungAsync() As System.Threading.Tasks.Task(Of Integer) Implements CustomCoffeeServiceReference.ICustomCoffeeService.BerechneEntfernungAsync
            Return MyBase.Channel.BerechneEntfernungAsync
        End Function
        
        Public Function BestelleKreation(ByVal pKreation As CustomCoffeeServiceReference.Kreation) As CustomCoffeeServiceReference.Auftrag Implements CustomCoffeeServiceReference.ICustomCoffeeService.BestelleKreation
            Return MyBase.Channel.BestelleKreation(pKreation)
        End Function
        
        Public Function BestelleKreationAsync(ByVal pKreation As CustomCoffeeServiceReference.Kreation) As System.Threading.Tasks.Task(Of CustomCoffeeServiceReference.Auftrag) Implements CustomCoffeeServiceReference.ICustomCoffeeService.BestelleKreationAsync
            Return MyBase.Channel.BestelleKreationAsync(pKreation)
        End Function
    End Class
End Namespace
